{% set name = "django-revproxy" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jazzband/django-revproxy/archive/{{ version }}.tar.gz
  sha256: c9b7b712a1b05c91f12ea4d374f5e4b458981f4a20962f46b0e4b1f7b5d9bd96

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.7
    - django >=3.0
    - urllib3 >=1.12
  run_constrained:
    - diazo >=1.0.5
    - lxml >=3.4

test:
  imports:
    - revproxy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jazzband/django-revproxy
  summary: Reverse Proxy view that supports all HTTP methods, Diazo transformations and Single Sign-On.
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
